//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        public int AracNo { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> Adet { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<int> Yıl { get; set; }
        public Nullable<int> SubeNo { get; set; }
        public Nullable<int> MüsteriNo { get; set; }
    }
}
