//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int KullaniciNo { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSifre { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Adres { get; set; }
        public string Mail { get; set; }
        public Nullable<int> SubeNo { get; set; }
    }
}
