//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int MusteriNo { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<int> Telefon { get; set; }
        public Nullable<System.DateTime> DTarih { get; set; }
        public Nullable<int> Bakiye { get; set; }
        public string Adres { get; set; }
    }
}
